# Distributed Log Analyzer Configuration

# System-wide settings
system:
  log_directory: "./logs"
  temp_directory: "./temp"
  max_workers: 8  # Default number of parallel processing workers
  debug_mode: false

# Log processing parameters
log_processing:
  chunk_size: 10000  # Number of log entries per processing batch
  supported_formats:
    - "json"
    - "csv"
    - "txt"

# Network configuration
network:
  host: "localhost"
  port: 8765
  timeout: 30  # Connection timeout in seconds
  max_connections: 50

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_log_size: 10485760  # 10 MB max log file size